@api = http://localhost:5000



# --- SAVINGS --- #

### Get all savings
GET {{api}}/savings

### Get a single saving
GET {{api}}/savings/608d3eb3a928f33c171a8f7f

### Create saving
POST {{api}}/savings
Content-Type: application/json

{
    "type": "cash",
    "description": "some cash",
    "amount": 600,
    "currency": "USD"
}

### Delete saving
DELETE {{api}}/savings/608d3eb7a928f33c171a8f80

### Update saving
PUT {{api}}/savings/608d443b5f572f417ff13bf1
Content-Type: application/json

{
    "amount": 200
}




# --- USERS --- #

### Get all users
GET {{api}}/users

### Get a single user
GET {{api}}/users/60904fbb255d65760cd8afed

### Delete user
DELETE {{api}}/users/609047c7f40cf372d2cc5762

### Update user
PUT {{api}}/users/609046988b5b7e72582be095
Content-Type: application/json

{
    "name": "hola"
}    



# --- AUTH --- #

### Register user
POST {{api}}/auth
Content-Type: application/json

{
    "name": "mau",
    "surname": "vie",
    "email": "mauricio.viera@trioteca.com",
    "password": "12345",
    "role": "admin"
}

### Login user
POST {{api}}/auth/login
Content-Type: application/json

{
    "email": "mauricio.vie@trioteca.com",
    "password": "12345"
}



# --- DASHBOARD --- #

### Dashboard
GET {{api}}/dashboard
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOTA0ZmJiMjU1ZDY1NzYwY2Q4YWZlZCIsIm5hbWUiOiJtYXUiLCJpYXQiOjE2MjA0ODM3MTQsImV4cCI6MTYyMDQ4MzczNH0.Dp1IV1yIUdXhaUP_V1vxqsuwyUvKqb02RDKDp112gpY